blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),
]

blog/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('post/<slug:slug>/', views.post, name='post'),
]

blog/post/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User


class Post(models.Model):
    class Publish(models.TextChoices):
        PUBLISHED = ('PB', 'Published')
        DRAFT = ('DR', 'Draft')

    UUID = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    images = models.ManyToManyField('Image', blank=True, related_name='posts')
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500)
    text = models.TextField()
    status = models.CharField(max_length=2, choices=Publish.choices, default=Publish.PUBLISHED)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ['-created']


class Image(models.Model):
    UUID = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    title = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to='post_images/')

blog/post/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def home(request):
    return render(request, 'post/home.html')


def posts(request):
    query = None
    posts = Post.objects.filter(status=Post.Publish.PUBLISHED)
    if 'search' in request.GET:
        query = request.GET['search']
        posts = posts.filter(title__icontains=query)

    return render(request, 'post/posts.html', {'posts': posts, 'query': query})

def post(request, slug):
    post = get_object_or_404(Post, slug=slug, status=Post.Publish.PUBLISHED)
    return render(request, 'post/post.html', {'post': post})

blog/post/templates/post/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Asosiy{% endblock %}
{% block content %}
<h2>Random picsum image for you</h2>
<div class="picsum-image">
    <img src="https://picsum.photos/1000/400" alt="Picsum image">
</div>
<h1>Welcome to my first blog site in django</h1>
<p class="home-p">I write about programming languages such as python and it's frameworks called django, aiogram and
    other built-in libraries</p>
<a class="btn home-btn" href="{% url 'post:posts' %}">Read blogs</a>
{% endblock %}

blog/post/templates/post/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/post/post.css' %}">
{% endblock %}
{% block content %}
<div class="post">
    <h1 class="title">{{ post.title }}</h1>
    <p class="username">@{{ post.user.username }}</p>
    <p class="date">{{ post.created }}</p>
    <p class="post-text">{{ post.text|safe }}</p>
</div>
<div class="card">
    <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias corrupti odio a dolor consequuntur nobis quod
        eius repellendus blanditiis vitae.
    </p>
</div>
{% endblock %}

blog/post/templates/post/posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Postlar{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/post/posts.css' %}">
{% endblock %}
{% block content %}
{% if query %}
<h2>"{{ query }}" bo'yicha topilgan postlar</h2>
{% endif %}
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <a href="{% url 'post:post' post.slug %}">
            <p class="date">{{ post.created|date:"M d, Y" }}</p>
            <p class="title">{{ post.title|truncatewords:10 }}</p>
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="uz">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/resources.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    {% block css %}{% endblock %}
</head>

<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="container">
        <p class="footer">Otabek N. 2024</p>
    </footer>
    <script src="{% static 'js/responsive.js' %}"></script>
    <script src="https://kit.fontawesome.com/6bef19a9f6.js" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/header.html
<header class="main-header container">
    <nav class="main-navigation">
        <div class="main-navigation__brand">
            <a class="main-navigation__logo" href="{% url 'post:home' %}">Otabek's Blog</a>
        </div>
        <button class="btn navbar-open" id="navbar-open">
            <i class="fa-solid fa-bars"></i>
        </button>
        <ul class="main-navigation__items">
            <li class="main-navigation__item"><a href="{% url 'post:home' %}">Asosiy</a></li>
            <li class="main-navigation__item"><a href="{% url 'post:posts' %}">Postlar</a></li>
            <form class="main-navigation__item" action="{% url 'post:posts' %}" method="get">
                <input class="search-input" type="search" name="search" placeholder="Search...">
                <button class="btn search-btn" type="submit">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </button>
            </form>
        </ul>
    </nav>
</header>

<ul class="main-navigation__items responsive" id="responsive-navbar">
    <li class="main-navigation__item"><a href="{% url 'post:home' %}">Asosiy</a></li>
    <li class="main-navigation__item"><a href="{% url 'post:posts' %}">Postlar</a></li>
    <form id="search-form" class="main-navigation__item" action="{% url 'post:posts' %}" method="get">
        <input id="search-input" class="search-input" type="search" name="search" placeholder="Search...">
    </form>
</ul>